package com.mediahub.iam.entity;

import jakarta.persistence.*;


@Entity
@Table(name = "roles")
public class Role {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long roleId;

    @Column(nullable = false, unique = true, length = 60)
    private String roleType;

    public Long getRoleId() { return roleId; }
    public void setRoleId(Long roleId) { this.roleId = roleId; }
    public String getRoleType() { return roleType; }
    public void setRoleType(String roleType) { this.roleType = roleType; }
}















// JPA entity mapped to the "roles" table; each instance is one role record.
// Represents a single role (e.g. "ADMIN", "USER") that can be assigned permissions and users.

// Primary key for the role; auto-generated by the database (IDENTITY/auto-increment).

// The role's name/type (e.g. "ADMIN"); required, must be unique, max 60 chars.

    // Getters and setters for each field, used by JPA and application code to read/write values.


