package com.mediahub.iam.entity;

import com.mediahub.iam.enums.UserStatus;
import jakarta.persistence.*;
import java.time.LocalDateTime;


@Entity
@Table(name = "users")
public class User {

    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long userId;


    @Column(nullable = false, length = 120)
    private String name;


    @ManyToOne
    @JoinColumn(name = "roleId", nullable = false)
    private Role role;

    @Column(nullable = false, unique = true, length = 255)
    private String email;

    @Column(length = 20)
    private String phone;

    // Optional 2-letter country code (e.g. "US", "IN").
    @Column(length = 2)
    private String country;


    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private UserStatus status = UserStatus.active;

    @Column(nullable = false, length = 255)
    private String passwordHash;

    
    @Column(length = 512)
    private String tokenHash;

    
    private LocalDateTime issuedAt;
    private LocalDateTime expiresAt;

    @Column(nullable = false)
    private Boolean isRevoked = false;

    private LocalDateTime revokedAt;

    @ManyToOne
    @JoinColumn(name = "revokedBy")
    private User revokedBy;

    
    @Column(columnDefinition = "TEXT")
    private String revocationReason;

    
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    
    private LocalDateTime updatedAt;

    
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    
    public Long getUserId() { return userId; }
    public void setUserId(Long userId) { this.userId = userId; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public Role getRole() { return role; }
    public void setRole(Role role) { this.role = role; }
    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }
    public String getPhone() { return phone; }
    public void setPhone(String phone) { this.phone = phone; }
    public String getCountry() { return country; }
    public void setCountry(String country) { this.country = country; }
    public UserStatus getStatus() { return status; }
    public void setStatus(UserStatus status) { this.status = status; }
    public String getPasswordHash() { return passwordHash; }
    public void setPasswordHash(String passwordHash) { this.passwordHash = passwordHash; }
    public String getTokenHash() { return tokenHash; }
    public void setTokenHash(String tokenHash) { this.tokenHash = tokenHash; }
    public LocalDateTime getIssuedAt() { return issuedAt; }
    public void setIssuedAt(LocalDateTime issuedAt) { this.issuedAt = issuedAt; }
    public LocalDateTime getExpiresAt() { return expiresAt; }
    public void setExpiresAt(LocalDateTime expiresAt) { this.expiresAt = expiresAt; }
    public Boolean getIsRevoked() { return isRevoked; }
    public void setIsRevoked(Boolean isRevoked) { this.isRevoked = isRevoked; }
    public LocalDateTime getRevokedAt() { return revokedAt; }
    public void setRevokedAt(LocalDateTime revokedAt) { this.revokedAt = revokedAt; }
    public User getRevokedBy() { return revokedBy; }
    public void setRevokedBy(User revokedBy) { this.revokedBy = revokedBy; }
    public String getRevocationReason() { return revocationReason; }
    public void setRevocationReason(String revocationReason) { this.revocationReason = revocationReason; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public LocalDateTime getUpdatedAt() { return updatedAt; }
}



























// @Entity, @Id @ManyToOne, @OneToMany etc are Hibernate Feautures used map Java classes to database tables.

// JPA entity mapped to the "users" table; each instance is one user account.
// Holds profile details, role, credentials, session token info, and revocation/audit timestamps.


// Primary key for the user; auto-generated by the database (IDENTITY/auto-increment).

// The user's display name; required, max 120 chars.

// Many-to-one link to the user's Role, joined via the "roleId" column (required).
// Defines what the user is authorized to do across the system.


// The user's email address; required, must be unique (used as the login identifier), max 255 chars.


// Optional contact phone number, max 20 chars.

// Account status (from the UserStatus enum), stored as its String name; defaults to "active".
// Required column, used to track whether the account is active, suspended, etc.


// The securely hashed login password; required, never stored in plain text, max 255 chars.


// Hash of the currently issued session/JWT token; optional, max 512 chars.


// Timestamps marking when the current token was issued and when it expires.


// Flag indicating whether the user's token/session has been revoked; required, defaults to false.

// Timestamp of when the token/session was revoked (null if never revoked).

// Many-to-one self-reference to the User (e.g. admin) who performed the revocation, via "revokedBy" column.

// Free-text reason for the revocation, stored as a TEXT column (nullable).

// Creation timestamp; required and never updated after insert (updatable = false).

// Timestamp of the most recent update to this record.

// JPA lifecycle callback run just before the entity is first persisted.
// Stamps both createdAt and updatedAt with the current time at creation.

// JPA lifecycle callback run just before each update to the entity.
// Refreshes updatedAt to the current time so it always reflects the last modification.

// Getters and setters for each field, used by JPA and application code to read/write values.
// Note createdAt and updatedAt are read-only (getters only) since they are managed automatically.
